### ISSUE TITLE
Fix display for "supporting" places on activity stream

### ISSUE THREAD

**Issue by futuresoup** [mapseed/platform#155]
Right now the activity stream shows an update when someone hits a the 'support' heart button and it looks bad. 

It has a broken image and is missing the name of the person supporting. It should at least say "someone supports..." but it's just missing entirely, so it just says "supports blah" instead of "someone supports blah"

I kind of think we should just get rid of it from the activity stream. It used to not be there, not sure how it started showing up.

If we do decide to keep it, I think it would look best if it said "[report title] was just supported"

**Comment by futuresoup** [comment]
Appears only to be happening when user is logged in as admin

**Comment by LukeSwart** [comment]
The broken image only occurs when the user is signed in as an admin (not Twitter or FB). Otherwise, if the user is not signed in, and they like/support a place, their action does not appear on the Activity Stream. If user is logged in on FB or Twitter, their profile pic is shown correctly.

So I guess the question is, do we still want to remove all likes/supports from the Activity Stream?

If not, then I agree that we should fix the bug where an admin's likes/supports have a broken profile pic. Or we can not include an admin's likes/supports from the Activity Stream altogether.
