### ISSUE TITLE
Sass integration with Django

### ISSUE THREAD

**Issue by LukeSwart** [mapseed/platform#348]
Right now we are using the `compass` command line tool to compile our SASS files into CSS. This works great, but it requires an extra step of having to install Ruby and the `compass` gem. It would be nice to integrate our SASS compiler with Django, which could make it easier for folks to contribute by not having to set up a Ruby dependencies on top of our existing Python stack. It would also provide more integrated functionality with our current projects,

To implement this, it looks like the `django-compressor` module handles SASS integration with Django, and the `django-libsass` module provides a C/C++ port of the Sass engine itself.

django-compressor docs: http://django-compressor.readthedocs.io/en/latest/settings/#django.conf.settings.COMPRESS_PRECOMPILERS

django-libsass: https://github.com/torchbox/django-libsass

Unfortunately, `django-compressor` dropped support for Django 1.7 in January 2016. We can either continue using the older version of this library (we are currently on 1.6), or wait until our Django 1.8 upgrade is complete to upgrade to the latest 2.0 version.

django-compressor changelog: http://django-compressor.readthedocs.io/en/latest/changelog/

**Comment by LukeSwart** [comment]
There is also this project: https://github.com/jrief/django-sass-processor that wraps libsass and django-compressor, but it seems to be having some issues with finding the right sass files.

**Comment by LukeSwart** [comment]
Here is the current implementation: https://github.com/smartercleanup/platform/tree/lukeswart/sass-conversion

**Comment by tlake** [comment]
Building off of Luke's branch, I'm working at https://github.com/smartercleanup/platform/tree/django-compressor-workflow on modifying our workflow to use Django Compressor to handle bundling and cachebusting of our static files. As of the commit at https://github.com/smartercleanup/platform/commit/9e7b9588a7bfb8afadd1630c126d341021a78a30 I've been going through our `base.html` and removing `{% if debug %}` switches on our CSS and JS tags, and instead wrapping those tags in `{% compress css/js %}` blocks.

Among other things to be done for this workflow, I'll need to edit our workflow to run `manage.py compress` instead of using the npm build scripts for bundling.

**Comment by LukeSwart** [comment]
Due to the issues with django-compressor and django-libsass, I think I will re-implement this PR using [node-sass](https://www.npmjs.com/package/node-sass). It could also be a good first step toward updating the static contents of our site using a generate/bundler based on node.
