### ISSUE TITLE
Mobile workflow adjustments

### ISSUE THREAD

**Issue by goldpbear** [mapseed/platform#443]
On mobile, we'd like to improve the way we use our screen real estate when geolocating and display the place form view:
- [x] The place form view should occupy a greater percentage of the screen after a user's location has been set
- [x] Move (or duplicate) geolocate button to the top of the place form view
- [x] Remove map footer content

**Comment by futuresoup** [comment]
A good [mockup](https://material.uplabs.com/posts/filters-interface-resources) here on some interaction ideas for workflow

**Comment by Bilal-io** [comment]
Hey guys, @futuresoup @goldpbear 
This is something I worked on tonight, give me some feedback and I'll make some changes if possible.
[Uploading HeyDuwamish-Mobile.pdf…](PDF FILE)
I will also try to create an interactive example based on these artboards in Adobe Xd.

**Comment by Bilal-io** [comment]
Here is some fake animation [http://adobe.ly/2dxfRHa](heyDuwamish Adobe Xd Project)
Not every button is clickable. (Click anywhere to get a hint)

**Comment by futuresoup** [comment]
This is looking good!! Nice work  :)

My two thoughts at the moment:

1) I want to make sure people have a way to get to the Stories explorer easily and don't miss that feature. It's the best way to discover content and be inclined to file a report because it will prompt the user on what kind of things they should be looking for and sharing to the map.

So we could try to find a way to get to the Stories explorer from the home screen though a simple button, though I like the simplicity of what you have. Or perhaps if enough of the map content triggers a story it will be good enough to get there. Or perhaps we have a default story show up on first run so they have a taste of it and can start navigating content without having to find it through the menu.

2) We need some mockups on how to walk the user through a good experience after hitting the "Add a report" button. Making sure they have a full map when choosing the location, but then have a full screen for filling out the actual form. Asking them to take a photo first so that gets out of the way, etc.

Really stoked about this! What do you think @PFeinson?

**Comment by goldpbear** [comment]
These look great! Thanks @Bilal-io.

I agree the simplicity of the design is appealing. I also like "Read more"/"Read less" workflow. I think this is more natural than the current expectation to scroll down to view more information about a selected place.

What if the "add a report button" were smaller and clung to the very bottom of the interface, both in map view and detail view? (We talked about that a bit last night.) That would free up even more map screen space, and it would encourage people to contribute new content no matter where they are in the story workflow (i.e. just browsing the map, browsing the detail preview mode, or looking at a full-screen detail view).
