### ISSUE TITLE
Lazy load image attachments

### ISSUE THREAD

**Issue by futuresoup** [mapseed/platform#451]
Our 12,000 Raingardens map - http://map.12000raingardens.org - is really slow because all the image attachments are being loaded at once, and there are thousands of them.

**Comment by zmbc** [comment]
Based on a little investigation with @justBanks, I think it is slow for a couple reasons. The first is that, as you said, the images are all loaded, which puts a lot of network strain on the device. But this is not the main usability problem; even while images are still loading, the map works fine.

What impacts usability the most is that Javascript freezes up the browser for between 6-10 seconds on my machine. According to the CPU profile, that time is largely spent in Marionette [rendering](http://marionettejs.com/docs/master/marionette.collectionview.html#collectionviews-render). If I understand this correctly, this is rendering the details of all the places.

So a two-birds-with-one-stone approach would be to only render the place's details at all when it gets clicked on. Of course, this would mean that all the `img` elements wouldn't get rendered right away either. I may try to do this, but it seems complicated and I'll have to learn more about Marionette. If anyone has any pointers, they would be appreciated.

**Comment by zmbc** [comment]
The Marionette rendering could also be rendering the list view. In that case, we could lazy-render by only rendering 10 or so at a time, and rendering more when the user scrolls to the bottom of the page.

**Comment by LukeSwart** [comment]
@zmbc Thanks for looking into this! Your explanation makes a lot of sense. I'd love to re-produce your CPU profile. What tool did you use? If you have time, can you send a screenshot of the profile?

I think the culprit here is `place-list-view`. Note that our `S.PlaceListItemView` extends Marionette's [Backbone.Marionette.Layout](http://marionettejs.com/docs/v1.6.1/marionette.layout.html) to render the place details, and the `S.PlaceListView` extends Marionette's [Backbone.Marionette.CompositeView](http://marionettejs.com/docs/v1.6.1/marionette.compositeview.html).

It looks like a good place to start is with the `PlaceListView.renderList` method.

I'm happy to discuss more and help out! Fixing this issue(s) would be a huge help :-)

**Comment by zmbc** [comment]
@LukeSwart I did the profile twice: once using [Chrome dev tools](https://developers.google.com/web/tools/chrome-devtools/profile/evaluate-performance/timeline-tool?hl=en) and once using [Firefox dev tools](https://developer.mozilla.org/en-US/docs/Tools/Performance). The results were basically the same.

I agree on further thought that it's almost definitely the list view that's the culprit (or one of the culprits, anyway). When you switch to the list tab, it's obvious that every single raingarden has already been rendered in that list.

Unfortunately I'm busy tomorrow so I won't be at the meetup, but I'm definitely interested in working on this.

**Comment by zmbc** [comment]
@LukeSwart said:



When the page initially loads, we are loading all of the images for all of our community reports. If we have lots of reports with images, this greatly affects performance. The images are stored in an AWS S3 bucket using the boto package. It would be nice to enable the ability to lazily load a place's image only when the place is selected.

For list view, we can limit the view to only ~10 places, or work with only the thumbnails. As the user scrolls, we can proceed to fetch those images.

See use case example for the 2800+ place records that are loading with slow performance at http://map.12000raingardens.org

This issue corresponds with this issue on our API: smartercleanup/api#8

...

As a quick first step, I think if we can prevent the attachments from loading by commenting out these lines here: https://github.com/smartercleanup/platform/blob/develop/src/sa_web/static/js/models.js#L161-L168

After that, we can work on loading the attachments only when the place is clicked (or when we enter the place list-view).

**Comment by goldpbear** [comment]
@zmbc @LukeSwart -- Looking more closely at Marionette's composite view, I noticed that it's designed to load items into a ["document fragment"](https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment) before final rendering. I was unfamiliar with this concept, but fragments seem to be a kind of mini-DOM, to which you can append nodes without triggering a repaint in the browser. Once all elements have been loaded into a fragment, then the entire fragment can be inserted into the real DOM in one go.

I haven't confirmed this yet, but I suspect that when our attachment `<img>` tags get added to the document fragment by Marionette the browser fetches the image content.

Zeb, you might have been on the right track when you thought there was a secondary DOM handling the image requests.

**Comment by zmbc** [comment]
@goldpbear thanks for looking into it. Yes, [document fragments initiate HTTP requests](http://stackoverflow.com/questions/12747350/using-documentfragment-to-parse-html-without-sending-http-requests). That's what's going on.

I'm super glad I understand this now, because I didn't want to rush into doing something without understanding the full system. But luckily this doesn't actually complicate the problem; we don't want to be rendering every list item, for the same two reasons that this issue was opened:

- Lots of unnecessary HTTP requests
- Lots of unnecessary work being done in the browser

So, moving forward, should we try to hack around in the Marionette CompositeView, or should we abandon it altogether? As @LukeSwart mentioned last week, we only use Marionette in the PlaceListView (although [it looks like we have expressed interest elsewhere](https://github.com/smartercleanup/platform/blob/606763921c273860ee405619ff2647a7de1ca71a/src/sa_web/static/js/views/activity-view.js#L32)). Thoughts?

**Comment by goldpbear** [comment]
It could make sense to get rid of marionette entirely, but I think it might be easier in this case to try and work around the default render behavior to suit our purposes, if only because it doesn't involve ripping out a piece of the infrastructure. I think we can short-circuit the default `render()` method in `PlaceListItemView` to suit our needs.

That said, if it turns out that we have to bend over backwards to get marionette to behave the way we want, then perhaps it should go.

**Comment by zmbc** [comment]
> if only because it doesn't involve ripping out a piece of the infrastructure.

This would be a good thing, imo.

If I have time, I'll take my (opinionated) shot at this tomorrow before we meet. We can discuss more in code review, but moving forward on this is important.

**Comment by goldpbear** [comment]
Sounds good! Yeah, I'd say if getting rid of marionette here turns out to be the more sensible thing to do, then I'd be all for it.
